vocab: Vocabulary
voc: Vocabulary
cv: Computer Vision
cg: Computer Graphivs
ml: Machine Learning
dl: Deep Learning
phi: Philosophy
psy: Psychology
cn: Computer Networking
bio: Biology
la: Linear Algebra
geo: Geography
wd: Web Development