vocab: Vocabulary
voc: Vocabulary
vb: Vocabulary
cv: Computer Vision
cg: Computer Graphics
ml: Machine Learning
dl: Deep Learning
phi: Philosophy
psy: Psychology
cn: Computer Networking
bio: Biology
la: Linear Algebra
geo: Geography
wd: Web Development
fit: Fitness
nu: Nutrition
av: Autonomous Vehicle
ppl: People
org: Organization
fin: Finance
py: Python
hi: History
rel: Religion
prob: Probability
de: Data Engineering
bo: Book
phr: Phrase
med: Medical
wo: Work
cal: Calculus
soc: Sociology
med: Medical
qp: Quantum Physics
ww2: WW2
rl: Reinforcement Learning
leg: Legal
cal: Calculus
ar: Art